name: DreamPlex

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build DreamPlex
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ['3.10','3.11']
    steps:
      - name: Install prerequisites
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt-get install -y build-essential autoconf autotools-dev gettext python${{ matrix.python }}-dev

      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Build DreamPlex python ${{ matrix.python }}
        run: |
          pip install six
          autoreconf -i
          ./configure
          make
          python -m compileall .
